django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # post앱의 index뷰를 root url에 연결시킨다.
    # url(r'^$', post_views.index),

    # 새 view를 만들어 redirect시키는 방법
    url(r'^$', views.index, name='index'),

    # Class-based View중 RedirectView를 사용하는 방법
    # url(r'^$', RedirectView.as_view(pattern_name='post:post_list')),

    # post앱의 urls.py모듈을 include시킨다
    url(r'^post/', include('post.urls')),
    url(r'^member/', include('member.urls')),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_app/member/urls.py
from django.conf.urls import url

from . import views

app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^login/facebook/$', views.facebook_login, name='facebook_login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    # profile view의 0번
    url(r'^profile/$', views.profile, name='my_profile'),
    url(r'^profile/edit/$', views.profile_edit,name='profile_edit'),
    url(r'^profile/(?P<user_pk>\d+)/$', views.profile, name='profile'),
    url(r'^follow_toggle/(?P<user_pk>\d+)/$', views.follow_toggle, name='follow_toggle'),
]

django_app/post/urls.py
from django.conf.urls import url
from . import views

# URL Namespace
# https://docs.djangoproject.com/en/1.11/topics/http/urls/#url-namespaces
app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),

    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),

    # post_create와 매칭
    url(r'^create/$', views.post_create, name='post_create'),

    # post_modify와 매칭
    url(r'^(?P<post_pk>\d+)/modify/$', views.post_modify, name='post_modify'),

    # post_delete와 매칭
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    # post_like와 매칭
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),

    # comment_create와 매칭
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),

    # comment_modify와 매칭
    url(r'^comment/(?P<comment_pk>\d+)/modify/$', views.comment_modify, name='comment_modify'),

    # comment_delete와 매칭
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),

    # hashtag_post_list와 매칭
    url(r'^tag/(?P<tag_name>\w+)/$', views.hashtag_post_list, name='hashtag_post_list'),

    url(r'^youtube/search/$', views.youtube_search, name='youtube_search'),
    url(r'^youtube/post/create/$', views.post_create_with_video, name='youtube_create')
    # 위쪽의 결과들과 매칭되지 않을 경우
    # url(r'^.*/$', views.post_anyway, name='post_anyway'),
]

django_app/templates/common/base.html
{% load static %}
<!--
	템플릿 상속
		https://docs.djangoproject.com/en/1.11/ref/templates/language/#template-inheritance

	static 태그
		https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#static
-->
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" href="{% static 'css/layout.css' %}">
	<link rel="stylesheet" href="{% static 'css/post.css' %}">
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">
	<title>Instagram</title>
</head>
<body>
	{% if messages %}
	<div class="message">
		{% for message in messages %}
		<div>{{ message }}</div>
		{% endfor %}
	</div>
	{% endif %}
	<div id="wrap">
		<header class="top-header">
			<nav>
				<div class="nav-left nav-item">
					<a href="{% url 'post:post_list' %}">
						<img src="{% static 'images/logo.png' %}" alt="">
					</a>
				</div>
				<div class="nav-center nav-item">
					<input type="text" placeholder="검색">
				</div>
				<div class="nav-right nav-item">
					<a href="#">
						<img src="{% static 'images/icon_explore.png' %}" alt="">
					</a>
					<a href="#">
						<img src="{% static 'images/icon_heart.png' %}" alt="">
					</a>
					<a href="{% url 'member:my_profile' %}">
						<img src="{% static 'images/icon_profile.png' %}" alt="">
					</a>
				</div>
			</nav>
			<nav>
				<!--
					로그인 되어있으면 <유저명>으로 로그인 중 표시
					안되어있으면 a태그로 로그인창으로 이동할 수 있는 링크 추가
				-->
				<div>
					{% if user.is_authenticated %}
					<a href="{% url 'post:post_create' %}" class="btn" style="float:left; margin-top: -7px;">사진올리기</a>

					<span>{{ user }}로 로그인 중</span>
					<a href="{% url 'member:logout' %}" class="btn">로그아웃</a>
					{% else %}
					<form action="{% url 'member:login' %}" method="POST" class="form-inline">
						{% csrf_token %}
						{{ login_form }}
						<button type="submit" class="btn">로그인</button>
						<a href="{% url 'member:signup' %}" class="btn">회원가입</a>
						<a href="https://www.facebook.com/v2.9/dialog/oauth?client_id={{ facebook_app_id }}&scope=user_friends,public_profile,email&redirect_uri={{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'member:facebook_login' %}" class="btn btn-primary">페이스북으로 로그인</a>
					</form>
					<!--<a href="{% url 'member:login' %}" class="btn">로그인</a>-->
					{% endif %}
				</div>
			</nav>
		</header>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</body>
</html>